﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using Refit;
using System.Threading.Tasks;
using VpdbAgent.Vpdb.Models;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace VpdbAgent.Vpdb
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIVpdbApi : IVpdbApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIVpdbApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual IObservable<UserFull> GetProfile()
        {
            var arguments = new object[] {  };
            return (IObservable<UserFull>) methodImpls["GetProfile"](Client, arguments);
        }

        public virtual IObservable<Game> GetGame(string gameId)
        {
            var arguments = new object[] { gameId };
            return (IObservable<Game>) methodImpls["GetGame"](Client, arguments);
        }

        public virtual Task<List<Release>> GetReleases()
        {
            var arguments = new object[] {  };
            return (Task<List<Release>>) methodImpls["GetReleases"](Client, arguments);
        }

        public virtual IObservable<Release> GetFullRelease(string releaseId)
        {
            var arguments = new object[] { releaseId };
            return (IObservable<Release>) methodImpls["GetFullRelease"](Client, arguments);
        }

        public virtual IObservable<Release> GetRelease(string releaseId)
        {
            var arguments = new object[] { releaseId };
            return (IObservable<Release>) methodImpls["GetRelease"](Client, arguments);
        }

        public virtual IObservable<List<Release>> GetReleasesBySize(long filesize,long threshold)
        {
            var arguments = new object[] { filesize,threshold };
            return (IObservable<List<Release>>) methodImpls["GetReleasesBySize"](Client, arguments);
        }

        public virtual IObservable<List<Release>> GetReleasesByIds(string releases)
        {
            var arguments = new object[] { releases };
            return (IObservable<List<Release>>) methodImpls["GetReleasesByIds"](Client, arguments);
        }

    }
}


